PROGRAM = STATEMENT, { STATEMENT } ;
STATEMENT = IMPORT_STATEMENT | FUNCTION_DEFINITION | IF_STATEMENT
          | RETURN_STATEMENT | EXPRESSION ;
IMPORT_STATEMENT = IMPORT_KEYWORD, OPEN_PAREN, PACKAGE_LIST, CLOSE_PAREN ;
IMPORT_KEYWORD = "import" ;
OPEN_PAREN = "(" ;
PACKAGE_LIST = PACKAGE_LIST_ITEM, { PACKAGE_LIST_ITEM } ;
PACKAGE_LIST_ITEM = PACKAGE_IDENTIFIER, COMMA ;
PACKAGE_IDENTIFIER = IDENTIFIER ;
IDENTIFIER = LETTER, { LETTER | DIGIT | UNDERSCORE } ;
LETTER = "A" | "B" | "C" | "D" | "E" | "F" | "G"
       | "H" | "I" | "J" | "K" | "L" | "M" | "N"
       | "O" | "P" | "Q" | "R" | "S" | "T" | "U"
       | "V" | "W" | "X" | "Y" | "Z" | "a" | "b"
       | "c" | "d" | "e" | "f" | "g" | "h" | "i"
       | "j" | "k" | "l" | "m" | "n" | "o" | "p"
       | "q" | "r" | "s" | "t" | "u" | "v" | "w"
       | "x" | "y" | "z" ;
DIGIT = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" ;
UNDERSCORE = "_" ;
COMMA = "," ;
FUNCTION_DEFINITION = FUNCTION_DECLARATOR, FUNCTION_NAME, OPEN_BRACE,
                      PROGRAM, CLOSE_BRACE
